### ISSUE TITLE
An und Ausschalten von Hyperion

### ISSUE THREAD

**Issue by LaGra011** [ruhigundrelaxed/iobroker.hyperion#1]
Hallo ruhigundrelaxed

ich habe deinen Adapter mal aufgespielt und er läuft super und stabil.
Zu meiner Frage. Wird es in zukünftigen Versionen möglich sein Hyperion
an und auszuschalten?

z.B: mit "hyperion-remote -color black" für aus? "-clearall" für an?

MfG LaGra

**Comment by ruhigundrelaxed** [comment]
Moin,

ja, das ist in meiner aktuellen Entwicklerversion schon implementiert. (Wie hyperion-remote, nur halt direkt über die json api.) Ich werde den code am Wochenende mal bereinigen und committen.  Außerdem habe ich noch hue, sat und lum implementiert. Alexa findet dann auch ein "hue" gerät. Allerdings muss ich noch herausfinden, wie ich die Werte zu interpretieren habe. Gruß
