### ISSUE TITLE
Start-Stop Integration

### ISSUE THREAD

**Issue by mikiline** [ruhigundrelaxed/ioBroker.hyperion#10]
hallo, erstmal vielen dank für die tolle arbeit.
wäre es möglich "start" und "stop" noch zu integrieren?

**Comment by ruhigundrelaxed** [comment]
Hmmm... So funktioniert hyperiond nicht.   Es gibt "clear" bzw. "clear_all". Das löscht die Daten bzgl. der Priorität. Was effektiv die Leds "blanked". Aber wenn du einen hyperion-x11 benutzt kommen die Daten nicht vom iobroker Adapter sondern vom hyperion-x11. Man könnte die Leds dann jedoch über den Adapter mit einer höheren prio schwarz setzten... Dies würde dann die Leds "blanken" bis wiederum ein "clear" bzw. "clear_all" kommt. (Oder ein hyperion-x11 mit höherer prio...) Beschreibe doch mal was genau du vor hast. Ich schaue dann, wie man das implementieren könnte...

**Comment by mikiline** [comment]
Hi, Danke für Deine Antwort.
Ich meine wie bei Hypercon, das man den Hyperion-Server stoppen und starten kann. Ich meine nicht die LEDs zurücksetzen oder so. Sorry wenn ich mich unverständlich ausgedrückt habe ;)
momentan hängt ja der Pi hinterm Fernseher.....wenn ich nicht schaue wird die Steckdose ausgeschalten, das der Pi nicht mehr läuft und auch keine LED leuchten. Das würde ich gerne mit einem "Stop" und "Start" lösen. Ist schonender als immer den Strom wegzunehmen am Pi.......

**Comment by ruhigundrelaxed** [comment]
Hi mikline,
das Starten und das Stoppen des Daemons möchte ich ungern in den Adapter einbauen. Dies hat 2 Gründe: 1.)  Es gibt mehrere Arten den Daemon zu starten und zu beenden. Hypercon startet und beendet auch nur den Dienst, den es auch konfiguriert und installiert hat. (afaik) Bei meiner Installation z.B.  laufen 8 Hyperion Dienste parallel die jeweils über systemd angestartet werden. Hypercon kann mit sowas nix anfangen, es würde den Prozess killen und mein systemd würde dies merken und ihn  wieder starten. 2.) Es macht auch nicht all zuviel Sinn, den Dienst zu stoppen. Wenn er keine Daten bekommt, liegt er ziemlich unauffällig im Speicher und verbraucht fast nix. 

Stell dir den HyperionAdapter wie deine Fernbedienung deines Fernsehers vor. Den kannst du dann mit der Fernbedienung auf "standby" schalten, aber niemals richtig aus. Wie sollte er sonst den Befehl "wache aus standby auf" empfangen können. 

Selbst für dein spezielles "use Szenario" sehe ich keinen Vorteil den Dienst zu stoppen. Dein Pi läuft ja weiter und du würdest ihn ja nach wie vor "hart" ausschalten müssen. (was man, je nach rootfs, vermeiden sollte).

Hier mal mein Ansatz um Strom zu sparen: Mein HTPC (libreelec) bekommt via iobroker den befehl: "Fernseher aus".  ioBroker sendet dann via ssh einen befehl an die kiste: "runterfahren (shutdown now -h)". ein paar Sekunden später schalte ich dann den Strom ab. 

Bei den LEDs schaltet iobroker jeweils das Netzteil ab, wenn sie nicht benötigt werden. Denn die LEDs haben ca. 6ma pro Stück(!!) standby. Also verbrauchen die LEDs den Strom unabhängig davon ob sie angesteuert werden oder nicht. Ob der dienst läuft oder nicht ist denen egal...

Ich mache hier mal zu. Weitere Fragen dann über FB oder das Forum. Ggf machen wir dann ein "issue" daraus... 
Gruß Martin

**Comment by LaGra011** [comment]
Erledige das an- und ausschalten doch über JavaScript.

z.B. zum ausschalten.

var net = require('net');
function sendMessage(host, port, message) {
  var client = net.connect({host:host, port: port}, function () {
    // 'connect' listener
    console.log('connected to server!');
    client.write(message);
  });
  client.on('data', function (data) {
    console.log(data.toString());
    client.end();
  });
  client.on('end', function () {
    console.log('disconnected from server');
  });
  client.on('error', function (error) {
    console.error('error: ' + error);
    client.end();
  });
}
sendMessage('192.168.1.205', 19444, '{ "color": [0,0,0], "command": "color", "priority": 100 }');

Du musst natürlich noch die IP anpassen.

**Comment by ruhigundrelaxed** [comment]
Naja, das kannst du mit dem Adapter auch machen. Du schaltest die Farbe auf "schwarz". (hyperion.0.control.activeColorRGB = #000000) oder die Helligkeit auf 0. (hyperion.0.control.activeColorLum = 0) oder du löschst einfach die Daten des Kanals. (hyperion.0.control.clear)...  Aber so richtig abschalten kannst du Hyperiond wie oben beschrieben halt nicht. Momentan überlege ich mir, ob ich eine Art "dynamischen" State baue, der über das Admin Interface konfigurierbar ist. Entweder schalte bei "aus" nur auf 0,0,0 und speichere vorher die Farbe in einer temp var oder mache genau das und zusätzlich setze noch einen "foreign" State eines Anderen Adapters z.B. einer Funksteckdose welche das Netzteil der LEDs steuert. Bei "an" dann vice versa.  Ich denke noch darüber nach. Besonders ratlos bin ich noch bei der Definition von "aus". Soll sich das dann nur auf die "Farbdarstellung" des Adapters beziehen, oder auf alles. Also prio 1 oder so...

**Comment by mikiline** [comment]
also......den Adapter selbst schalte ich auch ab sobald die Steckdose auch auf "aus" ist und mein Raspi nicht mehr an der Fritz angemeldet.
Da auf dem Raspi wirklich nur Hyperion läuft klau ich dem Teil einfach den Strom sobald meine Multimedia-Anlage in Standby geht.....

on({id: "tr-064.0.devices.Hyperion.active"/*active*/, change: "ne"}, function (obj) {
  var value = obj.state.val;
  var oldValue = obj.oldState.val;
  
  var obj_hyperion = getObject("system.adapter.hyperion.0");
  obj_hyperion.common.enabled = getState("tr-064.0.devices.Hyperion.active").val; // Adapter schalten
  setObject("system.adapter.hyperion.0", obj_hyperion);
});

**Comment by ruhigundrelaxed** [comment]
Hmmm... Mir ist der Sinn bzw. Unsinn einen Adapter zu stoppen nicht ganz klar. Das mag aber daran liegen, dass iobroker bei mir nicht auf einem Pi sondern auf einer "potenteren" Kiste läuft. Aus meiner Perspektive ist es egal ob der Adapter aktiviert ist oder nicht. Wenn der nix macht, verbraucht er zwar ein wenig Arbeitsspeicher (bei mir ~40Mb) aber sonst auch nix. Wenn dein "hyperion pi" aus ist, sollte der Adapter auf gelb gehen. Ich wage mal die Behauptung aufzustellen, dass selbst bei einem PI der Stromverbrauch absolut gleich ist, ob der Adapter nun läuft oder nicht. Aber wie in dem Post, vor dem Deinen, beschrieben könnte ich wenn gewünscht einen State im Adapter einbauen, der einen "proxy" für einen anderen AdapterState darstellt. Z.b.: einen State: control.power der wenn "true oder false" dann einen anderen fremden State steuert. (z.B. um eine Funksteckdose zu schalten oder sowas). In deinem konkreten Fall würde ich vom harten abschalten des pi's Abstand nehmen. Das geht 100x gut und dann zerschießt es dir das Dateisystem. Ich würde folgendes machen: Erstmal ein passwordless ssh zwischen iobroker server und pi einrichten. (http://www.linuxproblem.org/art_9.html)  Und dann mit "exec("ssh root@192.168.xxx.xxx shutdown now -h");" den pi runterfahren und ein paar sekunden später den Strom kappen. Alles nach gusto... Aber das hat nix mit dem Hyperion Adapter zu tun. Mann könnte über einen "start / stop linux computer adapter nachdenken, der sowas automatisiert....

**Comment by mikiline** [comment]
Im Grunde kam ich einfach darauf das ich keinen Strom mehr haben möchte, da ja das ganze <system mit dem Ambilight "selbst gebastelt" ist..... einfach aus Sicherheitsgründen. Wäre nicht der erste Kabelbrand der entsteht wenn niemand zu Hause ist oder am Schlafen ist.

Ich werde nun noch versuchen Deinen vorschlag mit dem runterfahren einzubauen bevor der Strom gekappt wird. Danke für den Anstoss ;)

**Comment by ruhigundrelaxed** [comment]
Ja, dass kann ich voll und ganz verstehen. Aber den ganzen Stunt: "obj_hyperion.common.enabled = getState("tr-064.0.devices.Hyperion.active").val; " kannst du dir sparen. Der Adapter ist nur Software, die kann nicht brennen. Aber negative Auswirkungen hat es imho auch nicht. Meinen Vorschlag mit dem Runterfahren kannst du natürlich nur einbauen, wenn iobroker auch die Spannungsversorgung deines Hyperion steuert. So wie ich deinen geposteten Code verstehe, überprüfst du via tr064 ob der pi noch hochgefahren ist und schaltest via js den Adapter ab. (was wie schon beschrieben weitestgehend effektfrei ist)  Also steuert bei dir die Stromversorgung den Event der was macht. Wenn dieser Event bei dir ausglöst wird, ist der Strom ja schon weg und demzufolge kannst du auch nix mehr runterfahren. Ich kenne jetzt deine Hardware nicht... Aber da ich auch keinen unnötigen Standby mag mach ich gleich mal ein Video von meiner Lösung und poste das hier...

**Comment by mikiline** [comment]
korrekt....nur baue ich nun das shutdown ein und schalte 2 oder 5 sek später den strom aus (mal schauen wie lang das runterfahren benötigt).

den adapter (ich weiss der kann nicht brennen ;)) schalte ich nur aus, das er eben nicht läuft. Ich hab ioBroker auf einem QNAP mit genügend Ressourcen am Laufen, also keinem pi ;)
So wie wir das nun besprochen haben ist es für mich die einfachste Lösung und es muss nichts hinzuprogrammiert werden......Danke für Eure Hilfe

**Comment by ruhigundrelaxed** [comment]
https://www.youtube.com/watch?v=ACeSNtSJrWo
