### ISSUE TITLE
logo änderungs Vorschlag

### ISSUE THREAD

**Issue by Matten-Matten** [ruhigundrelaxed/ioBroker.hyperion#11]
Hallo, ich hab mal den Rand entfernt und Die Bildgröße etwas kleiner gemacht. Vielleicht übernimmst du es ja.

![hyperion](https://user-images.githubusercontent.com/32074970/35970920-6cc74ad2-0ccc-11e8-92d8-3dc6c8197130.png)

Gruß
Matten-Matten

**Comment by ruhigundrelaxed** [comment]
Find ich gut. Danke
