### ISSUE TITLE
Priorität in Einstellungen?

### ISSUE THREAD

**Issue by Matten-Matten** [ruhigundrelaxed/ioBroker.hyperion#12]
Hallo, kannst du noch die Priorität mit in die Einstellungsmaske programieren

![iobroker admin-08 02 2018_19_20_09](https://user-images.githubusercontent.com/32074970/35990822-95e3ce34-0d05-11e8-9e15-417ac35cd275.png)

Das wäre super. Danke.

**Comment by ruhigundrelaxed** [comment]
Ja, ich bin mir noch nicht sicher. Im Admin oder als state. Was denkst du?

**Comment by Matten-Matten** [comment]
Ich würde es lieber im Admin packen, denn das stellt man ja einmal ein und dann ist gut.
 ich musste mir das jetzt in deinen configs einzeln raussuchen, da die priority noch auf 1 eingestellt ist,
 und ich das lieber auf 100 wollte. 

ich habs versucht heute zu integrieren (dich zu unterstützen), bin da aber seitens mangelnder Kenntnisse 
an meine grenzen gestoßen und habs leider nicht hinbekommen.

Schon mal schönen Dank, Super Arbeit.

Was mir noch aufgefallen ist, ich wollte bei `activeColorHue` eine Farbe einstellen, da tauchte nur folgende Fehlermeldungen auf:
`

host.tinkerboard | 2018-02-08 21:09:39.333 | error | instance system.adapter.hyperion.0 terminated with code 6 (uncaught exception)
-- | -- | -- | --
Caught | 2018-02-08 21:09:39.332 | error | by controller[0]: at Manager.ondata (/opt/iobroker/node_modules/socket.io-client/lib/manager.js:322:16)
Caught | 2018-02-08 21:09:39.332 | error | by controller[0]: at Decoder.add (/opt/iobroker/node_modules/socket.io-parser/index.js:246:12)
Caught | 2018-02-08 21:09:39.332 | error | by controller[0]: at Decoder.Emitter.emit (/opt/iobroker/node_modules/component-emitter/index.js:134:20)
Caught | 2018-02-08 21:09:39.331 | error | by controller[0]: at Decoder. (/opt/iobroker/node_modules/component-bind/index.js:21:15)
Caught | 2018-02-08 21:09:39.331 | error | by controller[0]: at Manager.ondecoded (/opt/iobroker/node_modules/socket.io-client/lib/manager.js:332:8)
Caught | 2018-02-08 21:09:39.331 | error | by controller[0]: at Manager.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
Caught | 2018-02-08 21:09:39.330 | error | by controller[0]: at Manager. (/opt/iobroker/node_modules/component-bind/index.js:21:15)
Caught | 2018-02-08 21:09:39.330 | error | by controller[0]: at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:236:12)
Caught | 2018-02-08 21:09:39.330 | error | by controller[0]: at Socket.onack (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:312:9)
Caught | 2018-02-08 21:09:39.327 | error | by controller[0]: at Number. (/opt/iobroker/node_modules/iobroker.hyperion/hyperion.js:107:38)
Caught | 2018-02-08 21:09:39.317 | error | by controller[0]: TypeError: Cannot read property 'val' of null
hyperion.0 | 2018-02-08 21:09:39.225 | info | cleaned everything up...
hyperion.0 | 2018-02-08 21:09:38.221 | info | cleaned everything up...
hyperion.0 | 2018-02-08 21:09:38.219 | error | at Manager.ondata (/opt/iobroker/node_modules/socket.io-client/lib/manager.js:322:16)
hyperion.0 | 2018-02-08 21:09:38.219 | error | at Decoder.add (/opt/iobroker/node_modules/socket.io-parser/index.js:246:12)
hyperion.0 | 2018-02-08 21:09:38.219 | error | at Decoder.Emitter.emit (/opt/iobroker/node_modules/component-emitter/index.js:134:20)
hyperion.0 | 2018-02-08 21:09:38.219 | error | at Decoder. (/opt/iobroker/node_modules/component-bind/index.js:21:15)
hyperion.0 | 2018-02-08 21:09:38.219 | error | at Manager.ondecoded (/opt/iobroker/node_modules/socket.io-client/lib/manager.js:332:8)
hyperion.0 | 2018-02-08 21:09:38.219 | error | at Manager.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
hyperion.0 | 2018-02-08 21:09:38.219 | error | at Manager. (/opt/iobroker/node_modules/component-bind/index.js:21:15)
hyperion.0 | 2018-02-08 21:09:38.219 | error | at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:236:12)
hyperion.0 | 2018-02-08 21:09:38.219 | error | at Socket.onack (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:312:9)
hyperion.0 | 2018-02-08 21:09:38.219 | error | at Number. (/opt/iobroker/node_modules/iobroker.hyperion/hyperion.js:107:38)
hyperion.0 | 2018-02-08 21:09:38.219 | error | TypeError: Cannot read property 'val' of null

`

**Comment by Matten-Matten** [comment]
Ich würde das dann wie folgt gestalten

![iobroker admin-08 02 2018_21_14_06](https://user-images.githubusercontent.com/32074970/35995967-52fd464e-0d15-11e8-8796-bd9520a3e711.png)

**Comment by ruhigundrelaxed** [comment]
Kannst du mal einen pull request deiner genialen admin/index.html stellen? Ich mach dann, dass das funktioniert. Bzgl. des Fehlers: HUE (0-360) wird zusammen  mit LUM und SAT in RGB umgerechnet. Ich vermute, dass ich da noch einen BUG drin habe. Du könntest mir mal sagen, ob die Werte SAT und LUM bei dir gesetzt waren. (Eigentlich sollte er 0 nehmen, falls ein Wert nicht vorhanden war...)

**Comment by ruhigundrelaxed** [comment]
Ich habe die nötigen Anpassungen durchgeführt. Scheint auch zu laufen. Ich werde das morgen mal ein wenig genauer testen und mich bemühen es ins "latest" zu bekommen. Aktuell also nur ungetestet via git. Da mein "design" im Gegensatz zu deinem doch eher Schrott ist würde ich gerne deine admin Seite übernehmen. Würde mich freuen, wenn du die beisteuern könntest. GUI ist nicht so meins...

**Comment by Matten-Matten** [comment]
Hier schon mal die zweite Grafik 

> ![hyperion2](https://user-images.githubusercontent.com/32074970/36001210-d8a5a0b0-0d25-11e8-9d4a-a0d13a3198a2.png)


Das kann ich doch eigentlich einfach forken oder? also wenn ich bei deiner index.html , auf bearbeiten gehe oder?

**Comment by ruhigundrelaxed** [comment]
Ja genau. Und genauso könntest du auch die Grafik hochladen. (Brauchst du nicht mehr, mache ich.)

**Comment by Matten-Matten** [comment]
Kannst du das mit der readme noch reinnehmen, dass man vom admin Adapter auf Github geleitet wird?

**Comment by ruhigundrelaxed** [comment]
Ja cool! Läuft... Nur noch die größe der Textboxen bei Chrome unter Linux...
![screen](https://user-images.githubusercontent.com/11939525/36002461-8ec9872c-0d2a-11e8-8c5f-d1cce17f832f.png) 

Was genau soll ich in die Readme aufnehmen? Verstehe ich nicht...

**Comment by Matten-Matten** [comment]
bei den text boxen mache ich gleich noch ein fork

und die Readme Verlinkung 
![iobroker admin-08 02 2018_23_53_07](https://user-images.githubusercontent.com/32074970/36002694-5a1f6a5e-0d2b-11e8-9575-7b0cf271f84b.png)

**Comment by Matten-Matten** [comment]
Die Priorität ist jetzt standardmäßig (ohne Eingabe ) auf 100 richtig?

**Comment by ruhigundrelaxed** [comment]
Ach das meinst du! Verstehe. Muss ich mal schauen, wo die readme verlinkt ist. Ich schätze irgendwo in der io-package.json.  Ja, 100 ist default!

**Comment by ruhigundrelaxed** [comment]
readme => done

**Comment by Matten-Matten** [comment]
zauberhaft 👍  default wert in der  Index =100

**Comment by ruhigundrelaxed** [comment]
Prima. Morgen teste ich das mal ausgiebig. Ich glaube das die priority auch das letzte fehlende "Feature" war. Somit kann ich dann, wenn morgen keine gröberen Fehler auftauchen mal: Version 0.1.0 raushauen. Also Beta! Vielen Dank für deine Hilfe. Bist du in der Facebook Gruppe oder im Forum unterwegs?

**Comment by Matten-Matten** [comment]
Habe kein Facebook (ja sowas gibts noch) ;)
Im IOBroker Forum ja  unter "Matten Matten"

**Comment by ruhigundrelaxed** [comment]
Ja, habe mich auch lange geweigert... Egal. Ich texte dich die Tage mal im Forum an. Vielen dank nochmal. Ich mach dann hier zu... :-)

**Comment by Matten-Matten** [comment]
http://forum.iobroker.net

Gruß Matze 👍
