### ISSUE TITLE
effects und control ohne funktion!

### ISSUE THREAD

**Issue by Matten-Matten** [ruhigundrelaxed/ioBroker.hyperion#15]
Moin, wenn man Hyperion auf ein frisches iobroker installiert beziehungsweise noch ohne einer vorherigen Version vom hyperion adapter  funktioniert effects und control nicht.

Gruß Matze.

**Comment by ruhigundrelaxed** [comment]
Hi Matze,
steht denn was in den Logs (debug)? Kann es sein, dass ein anderer Client mit höherer Prio was blockiert?
Gruß Martin

**Comment by Matten-Matten** [comment]
Da steht nichts außer:

> hyperion.0 | 2018-03-05 18:34:45.029 | info | Set effect: Rainbow swirl fast
> hyperion.0 | 2018-03-05 18:34:24.120 | info | Hooray! We are connected to hyperiond!
> hyperion.0 | 2018-03-05 18:34:24.104 | info | starting. Version 0.0.12 in C:/ioBroker/node_modules/iobroker.hyperion, node: v4.5.0

**Comment by Matten-Matten** [comment]
Das ist auch nur wenn man Hyperion auf ein frisches iobroker installiert beziehungsweise noch ohne einer vorherigen Version vom hyperion adapter

**Comment by Matten-Matten** [comment]
http://forum.iobroker.net/viewtopic.php?p=126996#p126996
Im Forum steht auch schon was. 
darauf hin hab ich mein hyperion Adapter verpackt und hoch geladen vieleicht findest du da was.

http://forum.iobroker.net/download/file.php?id=22982

**Comment by ruhigundrelaxed** [comment]
Ok. Das sollte es gewesen sein. Prio war ein String solle aber ein Int sein... Bitte mal testen.. :-)

**Comment by Matten-Matten** [comment]
0.0.13 Läuft vielen dank.
