### ISSUE TITLE
Fehler bei Farbauswahl

### ISSUE THREAD

**Issue by Matten-Matten** [ruhigundrelaxed/ioBroker.hyperion#16]
Moin, Ich bekomme immer folgenden Fehler wenn ich versuche eine Farbe oder Helligkeit zu setzen.
also bei: 
hyperion.0.control.activeColorHue
und
hyperion.0.control.activeColorLum

Adapter auf einem RPI 3 
Node.js: v6.13.1
NPM: 3.10.10
js-controller 1.2.3

```
hyperion.0 | 2018-03-23 21:51:31.946 | info | cleaned everything up...
-- | -- | -- | --
hyperion.0 | 2018-03-23 21:51:30.941 | info | cleaned everything up...
hyperion.0 | 2018-03-23 21:51:30.937 | error | at Manager.ondata (/opt/iobroker/node_modules/socket.io-client/lib/manager.js:322:16)
hyperion.0 | 2018-03-23 21:51:30.937 | error | at Decoder.add (/opt/iobroker/node_modules/socket.io-parser/index.js:246:12)
hyperion.0 | 2018-03-23 21:51:30.937 | error | at Decoder.Emitter.emit (/opt/iobroker/node_modules/component-emitter/index.js:134:20)
hyperion.0 | 2018-03-23 21:51:30.937 | error | at Decoder. (/opt/iobroker/node_modules/component-bind/index.js:21:15)
hyperion.0 | 2018-03-23 21:51:30.937 | error | at Manager.ondecoded (/opt/iobroker/node_modules/socket.io-client/lib/manager.js:332:8)
hyperion.0 | 2018-03-23 21:51:30.937 | error | at Manager.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
hyperion.0 | 2018-03-23 21:51:30.937 | error | at Manager. (/opt/iobroker/node_modules/component-bind/index.js:21:15)
hyperion.0 | 2018-03-23 21:51:30.937 | error | at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:236:12)
hyperion.0 | 2018-03-23 21:51:30.937 | error | at Socket.onack (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:312:9)
hyperion.0 | 2018-03-23 21:51:30.937 | error | at Number. (/opt/iobroker/node_modules/iobroker.hyperion/hyperion.js:107:38)
hyperion.0 | 2018-03-23 21:51:30.937 | error | TypeError: Cannot read property 'val' of null
hyperion.0 | 2018-03-23 21:51:30.935 | error | uncaught exception: Cannot read property 'val' of null
```

**Comment by ruhigundrelaxed** [comment]
Oh ja, danke! Ich hab das mal gefixed. Gruß

**Comment by Matten-Matten** [comment]
Ok danke, 

wenn ich clearall betätige kommt folgende Meldung:


`hyperion.0 | 2018-03-26 14:11:21.674 | warn | Clearing all prios failed! The error code is: {"info":{"activeEffects":[],"activeLedColor":[],"adjustment":[{"blueAdjust":[0,0,255],"greenAdjust":[66,255,0],"id":"default","redAdjust":[255,15,0]}],"c
`
Ist das okay?

**Comment by ruhigundrelaxed** [comment]
Dieser Fehler ist schonmal im Forum aufgetaucht. Ich konnte ihn bisher nicht reproduzieren. Der Fehler kommt direkt aus Hyprion. Kommt das denn jedesmal, wenn du auf "clear all" drückst?

**Comment by Matten-Matten** [comment]
Ja jedesmal. 
Ist auch nur beim RPI 3
Node.js: v6.13.1
NPM: 3.10.10
js-controller 1.2.3
-------------------
bei meinem Tinker Board ist das nicht.

**Comment by ruhigundrelaxed** [comment]
Hmm. Ok. Funktioniert denn "clear all" trotzdem?

**Comment by Matten-Matten** [comment]
Ja! "clear all" funst trotzdem.

**Comment by ruhigundrelaxed** [comment]
Hmmm... Dein Rpi und dein Tinker Board gehen auf den gleichen HyperionD? Oder sind das unterschiedliche hyperion Instanzen? Ich bin geneigt für diesen Fehler einfach nur das Loglevel zu ändern, da es ja anscheinend ein "false positive" ist.

**Comment by Matten-Matten** [comment]
Sowohl der rpi als auch das Tinker Board steuern das selbe hyperion an.

**Comment by Matten-Matten** [comment]
Habs jetzt auch noch mal mit nem Hyperion Adapter auf mein WIN 10 getestet, auch da der Fehler

`

hyperion.0 | 2018-03-26 16:40:34.227 | warn | Clearing all prios failed! The error code is: {"info":{"activeEffects":[],"activeLedColor":[],"adjustment":[{"blueAdjust":[20,0,255],"greenAdjust":[70,255,0],"id":"default","redAdjust":[255,11,0]}],"
-- | -- | -- | --


`

**Comment by Matten-Matten** [comment]
`Ich bin geneigt für diesen Fehler einfach nur das Loglevel zu ändern, da es ja anscheinend ein "false positive" ist`
Da ja alles funktioniert würde ich das auch ignorieren.

**Comment by ruhigundrelaxed** [comment]
Ok! Ich habe das logging nun so umgebaut:
Wird ein err object zurück gegeben, gibt es die gleiche Meldung 
(`adapter.log.info("Clearing all prios on hyperion!")`), 
wie wenn keine err Object zurückgegeben wird plus dem Zusatz, dass es ignorierte Fehler gab. 
`(adapter.log.info("Clearing all prios on hyperion! (with ignored err: watch debug)")`
Und einen Hinweis, im Debug level nachzuschauen. 
Im Debug level erscheint dann eine detaliertere Meldung.
`adapter.log.debug("Clear all throws an error. Ignore if its working! Otherwise : " + JSON.stringify(err))`
