### ISSUE TITLE
Cant Connect to Hyperion - But through webinterface it works

### ISSUE THREAD

**Issue by TheRegiiX** [ruhigundrelaxed/ioBroker.hyperion#25]
Hallo,
Danke erstmal für das erstellen des Adapters!
Leider bekomme ich ihn nicht zum laufen.
Die IP und Port sollten richtig sein, da ich über die Android App und das Webinterface Zugriff auf die Hyperionsteuerung habe.
Ich bekomme in meinem Log immer folgende Fehlermeldung:

> 

host.ioBroker-RasPi | 2019-02-13 18:52:40.957 | info | Restart adapter system.adapter.hyperion.0 because enabled
-- | -- | -- | --
host.ioBroker-RasPi | 2019-02-13 18:52:40.957 | error | instance system.adapter.hyperion.0 terminated with code 0 (OK)
host.ioBroker-RasPi | 2019-02-13 18:52:40.957 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.hyperion/node_modules/color-convert/index.js:1:83)
host.ioBroker-RasPi | 2019-02-13 18:52:40.956 | error | Caught by controller[0]: at require (internal/module.js:20:19)
host.ioBroker-RasPi | 2019-02-13 18:52:40.956 | error | Caught by controller[0]: at Module.require (module.js:504:17)
host.ioBroker-RasPi | 2019-02-13 18:52:40.956 | error | Caught by controller[0]: at Function.Module._load (module.js:445:3)
host.ioBroker-RasPi | 2019-02-13 18:52:40.956 | error | Caught by controller[0]: at tryModuleLoad (module.js:453:12)
host.ioBroker-RasPi | 2019-02-13 18:52:40.955 | error | Caught by controller[0]: at Module.load (module.js:494:32)
host.ioBroker-RasPi | 2019-02-13 18:52:40.955 | error | Caught by controller[0]: at Object.Module._extensions..js (module.js:586:10)
host.ioBroker-RasPi | 2019-02-13 18:52:40.955 | error | Caught by controller[0]: at Module._compile (module.js:549:28)
host.ioBroker-RasPi | 2019-02-13 18:52:40.955 | error | Caught by controller[0]: at Object.runInThisContext (vm.js:97:10)
host.ioBroker-RasPi | 2019-02-13 18:52:40.955 | error | Caught by controller[0]: at createScript (vm.js:56:10)
host.ioBroker-RasPi | 2019-02-13 18:52:40.954 | error | Caught by controller[0]: SyntaxError: Unexpected token *
host.ioBroker-RasPi | 2019-02-13 18:52:40.954 | error | Caught by controller[0]: ^
host.ioBroker-RasPi | 2019-02-13 18:52:40.954 | error | Caught by controller[0]: ((x[0] - y[0]) ** 2) +
host.ioBroker-RasPi | 2019-02-13 18:52:40.953 | error | Caught by controller[0]: /opt/iobroker/node_modules/iobroker.hyperion/node_modules/color-convert/conversions.js:171
hyperion.0 | 2019-02-13 18:52:40.862 | info | starting. Version 0.0.15 in /opt/iobroker/node_modules/iobroker.hyperion, node: v6.14.3
host.ioBroker-RasPi | 2019-02-13 18:52:38.835 | info | instance system.adapter.hyperion.0 started with pid 17585
host.ioBroker-RasPi | 2019-02-13 18:52:38.791 | info | object change system.adapter.hyperion.0
host.ioBroker-RasPi | 2019-02-13 18:52:20.050 | info | Restart adapter system.adapter.hyperion.0 because enabled

**Comment by ruhigundrelaxed** [comment]
Hmmm... Da scheint was mit der Farbkonvertierung schief zu laufen. Kannst du mal logging auf debug stellen und mal posten was da bei hue, sat, lum steht? Wann kommt der Fehler? Direkt, wenn der Adapter startet, oder wenn du versuchst eine Farbe zu wechseln? Werden denn die States des Adapters erstellt? Gruß

**Comment by TheRegiiX** [comment]
Hey,
Die Fehler kommen direkt wenn ich den adapter starte und die states werden soweit ich das sehe auch erstellt.
Hier mal der debug log:

host.ioBroker-RasPi	2019-02-15 13:04:45.424	info	Restart adapter system.adapter.hyperion.0 because enabled
host.ioBroker-RasPi	2019-02-15 13:04:45.424	error	instance system.adapter.hyperion.0 terminated with code 0 (OK)
host.ioBroker-RasPi	2019-02-15 13:04:45.423	error	Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.hyperion/node_modules/color-convert/index.js:1:83)
host.ioBroker-RasPi	2019-02-15 13:04:45.423	error	Caught by controller[0]: at require (internal/module.js:20:19)
host.ioBroker-RasPi	2019-02-15 13:04:45.423	error	Caught by controller[0]: at Module.require (module.js:504:17)
host.ioBroker-RasPi	2019-02-15 13:04:45.423	error	Caught by controller[0]: at Function.Module._load (module.js:445:3)
host.ioBroker-RasPi	2019-02-15 13:04:45.423	error	Caught by controller[0]: at tryModuleLoad (module.js:453:12)
host.ioBroker-RasPi	2019-02-15 13:04:45.423	error	Caught by controller[0]: at Module.load (module.js:494:32)
host.ioBroker-RasPi	2019-02-15 13:04:45.422	error	Caught by controller[0]: at Object.Module._extensions..js (module.js:586:10)
host.ioBroker-RasPi	2019-02-15 13:04:45.422	error	Caught by controller[0]: at Module._compile (module.js:549:28)
host.ioBroker-RasPi	2019-02-15 13:04:45.422	error	Caught by controller[0]: at Object.runInThisContext (vm.js:97:10)
host.ioBroker-RasPi	2019-02-15 13:04:45.422	error	Caught by controller[0]: at createScript (vm.js:56:10)
host.ioBroker-RasPi	2019-02-15 13:04:45.422	error	Caught by controller[0]: SyntaxError: Unexpected token *
host.ioBroker-RasPi	2019-02-15 13:04:45.422	error	Caught by controller[0]: ^
host.ioBroker-RasPi	2019-02-15 13:04:45.421	error	Caught by controller[0]: ((x[0] - y[0]) ** 2) +
host.ioBroker-RasPi	2019-02-15 13:04:45.421	error	Caught by controller[0]: /opt/iobroker/node_modules/iobroker.hyperion/node_modules/color-convert/conversions.js:171
hyperion.0	2019-02-15 13:04:45.317	info	starting. Version 0.0.15 in /opt/iobroker/node_modules/iobroker.hyperion, node: v6.14.3
host.ioBroker-RasPi	2019-02-15 13:04:43.361	info	instance system.adapter.hyperion.0 started with pid 16245
host.ioBroker-RasPi	2019-02-15 13:04:13.339	info	Restart adapter system.adapter.hyperion.0 because enabled
host.ioBroker-RasPi	2019-02-15 13:04:13.338	error	instance system.adapter.hyperion.0 terminated with code 0 (OK)
Caught	2019-02-15 13:04:13.338	error	by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.hyperion/node_modules/color-convert/index.js:1:83)
Caught	2019-02-15 13:04:13.338	error	by controller[0]: at require (internal/module.js:20:19)
Caught	2019-02-15 13:04:13.338	error	by controller[0]: at Module.require (module.js:504:17)
Caught	2019-02-15 13:04:13.338	error	by controller[0]: at Function.Module._load (module.js:445:3)
Caught	2019-02-15 13:04:13.337	error	by controller[0]: at tryModuleLoad (module.js:453:12)
Caught	2019-02-15 13:04:13.337	error	by controller[0]: at Module.load (module.js:494:32)
Caught	2019-02-15 13:04:13.337	error	by controller[0]: at Object.Module._extensions..js (module.js:586:10)
Caught	2019-02-15 13:04:13.337	error	by controller[0]: at Module._compile (module.js:549:28)
Caught	2019-02-15 13:04:13.337	error	by controller[0]: at Object.runInThisContext (vm.js:97:10)
Caught	2019-02-15 13:04:13.337	error	by controller[0]: at createScript (vm.js:56:10)
Caught	2019-02-15 13:04:13.336	error	by controller[0]: SyntaxError: Unexpected token *
Caught	2019-02-15 13:04:13.336	error	by controller[0]: ^
Caught	2019-02-15 13:04:13.336	error	by controller[0]: ((x[0] - y[0]) ** 2) +
Caught	2019-02-15 13:04:13.335	error	by controller[0]: /opt/iobroker/node_modules/iobroker.hyperion/node_modules/color-convert/conversions.js:171
hyperion.0	2019-02-15 13:04:13.318	info	terminating
hyperion.0	2019-02-15 13:04:13.209	info	starting. Version 0.0.15 in /opt/iobroker/node_modules/iobroker.hyperion, node: v6.14.3
hyperion.0	2019-02-15 13:04:12.990	info	States connected to redis: 127.0.0.1:6379
hyperion.0	2019-02-15 13:04:12.978	debug	statesDB connected
hyperion.0	2019-02-15 13:04:12.932	debug	objectDB connected
hyperion.0	2019-02-15 13:04:12.812	error	at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.hyperion/node_modules/color-convert/index.js:1:83)
hyperion.0	2019-02-15 13:04:12.812	error	at require (internal/module.js:20:19)
hyperion.0	2019-02-15 13:04:12.812	error	at Module.require (module.js:504:17)
hyperion.0	2019-02-15 13:04:12.812	error	at Function.Module._load (module.js:445:3)
hyperion.0	2019-02-15 13:04:12.812	error	at tryModuleLoad (module.js:453:12)
hyperion.0	2019-02-15 13:04:12.812	error	at Module.load (module.js:494:32)
hyperion.0	2019-02-15 13:04:12.812	error	at Object.Module._extensions..js (module.js:586:10)
hyperion.0	2019-02-15 13:04:12.812	error	at Module._compile (module.js:549:28)
hyperion.0	2019-02-15 13:04:12.812	error	at Object.runInThisContext (vm.js:97:10)
hyperion.0	2019-02-15 13:04:12.812	error	at createScript (vm.js:56:10)
hyperion.0	2019-02-15 13:04:12.812	error	SyntaxError: Unexpected token *
hyperion.0	2019-02-15 13:04:12.812	error	^
hyperion.0	2019-02-15 13:04:12.812	error	((x[0] - y[0]) ** 2) +
hyperion.0	2019-02-15 13:04:12.812	error	/opt/iobroker/node_modules/iobroker.hyperion/node_modules/color-convert/conversions.js:171
hyperion.0	2019-02-15 13:04:12.798	error	uncaught exception: Unexpected token *
host.ioBroker-RasPi	2019-02-15 13:04:11.217	info	instance system.adapter.hyperion.0 started with pid 16235

**Comment by ruhigundrelaxed** [comment]
Zieh dir mal die aktuelle hyprion.js und probiers mal aus. Ich vermute, dass er mit leeren Werten für hue, sat und / oder lum versucht eine Farbkonvertierung durchzuführen. Dies verhindere ich nun... Ich vermute, dass deine States zwar erzeugt, aber nicht initialisiert wurden. Somit steht in besagten states unter control "" also nix drin. Wenn er dann versucht den Wert für RGB zu errechnen fällt er auf die Nase. Du kannst das gerne mal verifizieren, indem du manuell die werte von hue (0-360) sat und lum (0-100) setzt und dann den Adapter startest. Wenn ich recht habe, ist der  Fehler damit behoben. Oder halt die aktuelle Version, die für falsy werte (also "" bzw. undefined) den wert 0 annimmt. Bitte probieren, und mir bescheid geben ob ich richtig lag... Gruß

**Comment by TheRegiiX** [comment]
Ich hab beides versucht aber es kommt immer noch die gleiche Fehlermeldung.


host.ioBroker-RasPi | 2019-02-18 11:46:05.322 | info | Restart adapter system.adapter.hyperion.0 because enabled
-- | -- | -- | --
host.ioBroker-RasPi | 2019-02-18 11:46:05.322 | error | instance system.adapter.hyperion.0 terminated with code 0 (OK)
host.ioBroker-RasPi | 2019-02-18 11:46:05.322 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.hyperion/node_modules/color-convert/index.js:1:83)
host.ioBroker-RasPi | 2019-02-18 11:46:05.322 | error | Caught by controller[0]: at require (internal/module.js:20:19)
host.ioBroker-RasPi | 2019-02-18 11:46:05.322 | error | Caught by controller[0]: at Module.require (module.js:504:17)
host.ioBroker-RasPi | 2019-02-18 11:46:05.322 | error | Caught by controller[0]: at Function.Module._load (module.js:445:3)
host.ioBroker-RasPi | 2019-02-18 11:46:05.321 | error | Caught by controller[0]: at tryModuleLoad (module.js:453:12)
host.ioBroker-RasPi | 2019-02-18 11:46:05.321 | error | Caught by controller[0]: at Module.load (module.js:494:32)
host.ioBroker-RasPi | 2019-02-18 11:46:05.321 | error | Caught by controller[0]: at Object.Module._extensions..js (module.js:586:10)
host.ioBroker-RasPi | 2019-02-18 11:46:05.321 | error | Caught by controller[0]: at Module._compile (module.js:549:28)
host.ioBroker-RasPi | 2019-02-18 11:46:05.320 | error | Caught by controller[0]: at Object.runInThisContext (vm.js:97:10)
host.ioBroker-RasPi | 2019-02-18 11:46:05.320 | error | Caught by controller[0]: at createScript (vm.js:56:10)
host.ioBroker-RasPi | 2019-02-18 11:46:05.320 | error | Caught by controller[0]: SyntaxError: Unexpected token *
host.ioBroker-RasPi | 2019-02-18 11:46:05.320 | error | Caught by controller[0]: ^
host.ioBroker-RasPi | 2019-02-18 11:46:05.320 | error | Caught by controller[0]: ((x[0] - y[0]) ** 2) +
host.ioBroker-RasPi | 2019-02-18 11:46:05.319 | error | Caught by controller[0]: /opt/iobroker/node_modules/iobroker.hyperion/node_modules/color-convert/conversions.js:171
hyperion.0 | 2019-02-18 11:46:05.230 | info | starting. Version 0.0.15 in /opt/iobroker/node_modules/iobroker.hyperion, node: v6.14.3
host.ioBroker-RasPi | 2019-02-18 11:46:03.156 | info | instance system.adapter.hyperion.0 started with pid 910
host.ioBroker-RasPi | 2019-02-18 11:46:00.650 | info | instance system.adapter.hyperion.0 terminated with code null ()
host.ioBroker-RasPi | 2019-02-18 11:46:00.649 | warn | instance system.adapter.hyperion.0 terminated due to SIGTERM
host.ioBroker-RasPi | 2019-02-18 11:46:00.624 | info | stopInstance system.adapter.hyperion.0 killing pid 856
host.ioBroker-RasPi | 2019-02-18 11:46:00.623 | info | stopInstance system.adapter.hyperion.0
host.ioBroker-RasPi | 2019-02-18 11:46:00.619 | info | object change system.adapter.hyperion.0
host.ioBroker-RasPi | 2019-02-18 11:45:59.465 | info | instance system.adapter.hyperion.0 started with pid 856
host.ioBroker-RasPi | 2019-02-18 11:45:59.421 | info | object change system.adapter.hyperion.0
host.ioBroker-RasPi | 2019-02-18 11:45:34.915 | info | Restart adapter system.adapter.hyperion.0 because enabled

**Comment by TheRegiiX** [comment]
Mit folgenden States:

![hyperion_adapter_states](https://user-images.githubusercontent.com/37410875/52948008-9b883d80-3378-11e9-9752-544df0090d69.PNG)

**Comment by ruhigundrelaxed** [comment]
Oh ok. Kannst du mal activecolorRGB auf "#000000" und mal schauen, ob der adapter dann startet?

**Comment by TheRegiiX** [comment]
Immer noch:


  |   |   |  
-- | -- | -- | --
host.ioBroker-RasPi | 2019-02-18 13:09:09.748 | info | object change system.adapter.hyperion.0
host.ioBroker-RasPi | 2019-02-18 13:08:55.988 | info | Restart adapter system.adapter.hyperion.0 because enabled
host.ioBroker-RasPi | 2019-02-18 13:08:55.987 | error | instance system.adapter.hyperion.0 terminated with code 0 (OK)
Caught | 2019-02-18 13:08:55.987 | error | by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.hyperion/node_modules/color-convert/index.js:1:83)
Caught | 2019-02-18 13:08:55.987 | error | by controller[0]: at require (internal/module.js:20:19)
Caught | 2019-02-18 13:08:55.987 | error | by controller[0]: at Module.require (module.js:504:17)
Caught | 2019-02-18 13:08:55.987 | error | by controller[0]: at Function.Module._load (module.js:445:3)
Caught | 2019-02-18 13:08:55.986 | error | by controller[0]: at tryModuleLoad (module.js:453:12)
Caught | 2019-02-18 13:08:55.986 | error | by controller[0]: at Module.load (module.js:494:32)
Caught | 2019-02-18 13:08:55.986 | error | by controller[0]: at Object.Module._extensions..js (module.js:586:10)
Caught | 2019-02-18 13:08:55.986 | error | by controller[0]: at Module._compile (module.js:549:28)
Caught | 2019-02-18 13:08:55.986 | error | by controller[0]: at Object.runInThisContext (vm.js:97:10)
Caught | 2019-02-18 13:08:55.986 | error | by controller[0]: at createScript (vm.js:56:10)
Caught | 2019-02-18 13:08:55.986 | error | by controller[0]: SyntaxError: Unexpected token *
Caught | 2019-02-18 13:08:55.985 | error | by controller[0]: ^
Caught | 2019-02-18 13:08:55.985 | error | by controller[0]: ((x[0] - y[0]) ** 2) +
Caught | 2019-02-18 13:08:55.984 | error | by controller[0]: /opt/iobroker/node_modules/iobroker.hyperion/node_modules/color-convert/conversions.js:171
hyperion.0 | 2019-02-18 13:08:55.966 | info | terminating
hyperion.0 | 2019-02-18 13:08:55.854 | info | starting. Version 0.0.15 in /opt/iobroker/node_modules/iobroker.hyperion, node: v6.14.3
hyperion.0 | 2019-02-18 13:08:55.636 | info | States connected to redis: 127.0.0.1:6379
hyperion.0 | 2019-02-18 13:08:55.624 | debug | statesDB connected
hyperion.0 | 2019-02-18 13:08:55.578 | debug | objectDB connected
hyperion.0 | 2019-02-18 13:08:55.457 | error | at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.hyperion/node_modules/color-convert/index.js:1:83)
hyperion.0 | 2019-02-18 13:08:55.457 | error | at require (internal/module.js:20:19)
hyperion.0 | 2019-02-18 13:08:55.457 | error | at Module.require (module.js:504:17)
hyperion.0 | 2019-02-18 13:08:55.457 | error | at Function.Module._load (module.js:445:3)
hyperion.0 | 2019-02-18 13:08:55.457 | error | at tryModuleLoad (module.js:453:12)
hyperion.0 | 2019-02-18 13:08:55.457 | error | at Module.load (module.js:494:32)
hyperion.0 | 2019-02-18 13:08:55.457 | error | at Object.Module._extensions..js (module.js:586:10)
hyperion.0 | 2019-02-18 13:08:55.457 | error | at Module._compile (module.js:549:28)
hyperion.0 | 2019-02-18 13:08:55.457 | error | at Object.runInThisContext (vm.js:97:10)
hyperion.0 | 2019-02-18 13:08:55.457 | error | at createScript (vm.js:56:10)
hyperion.0 | 2019-02-18 13:08:55.457 | error | SyntaxError: Unexpected token *
hyperion.0 | 2019-02-18 13:08:55.457 | error | ^
hyperion.0 | 2019-02-18 13:08:55.457 | error | ((x[0] - y[0]) ** 2) +
hyperion.0 | 2019-02-18 13:08:55.457 | error | /opt/iobroker/node_modules/iobroker.hyperion/node_modules/color-convert/conversions.js:171
hyperion.0 | 2019-02-18 13:08:55.444 | error | uncaught exception: Unexpected token *
host.ioBroker-RasPi | 2019-02-18 13:08:53.894 | info | instance system.adapter.hyperion.0 started with pid 6229

**Comment by ruhigundrelaxed** [comment]
Das ist schon ein wenig komisch... Kannst du mir mal die zeile 171(+-5) von /opt/iobroker/node_modules/iobroker.hyperion/node_modules/color-convert/conversions.js posten? etwa mit: 
`head -n172 /opt/iobroker/node_modules/iobroker.hyperion/node_modules/color-convert/conversions.js | tail -n5`

**Comment by ruhigundrelaxed** [comment]
Ok... Irgendwie hat es den Anschein, dass dein color-convert nicht kompatibel zu deiner Nodejs Version ist. Ich benutze hier eine ältere Version von color-convert (1.9.1) und du nutzt allen Anschein nach 2.0.0. Zumindest sieht der Part: ((x[0] - y[0]) ** 2) + in der conversion.js bei mir anders aus. Welche Node version hast du? Ansonsten wäre die Lösung, die Library in der version 1.9.1 zu installieren. (Aber immer vorher ein Backup des iobroker Ordners machen. Mir hat npm schon mehr als einmal die komplette Installation geschossen.) Gruß

**Comment by ruhigundrelaxed** [comment]
Noch ein paar zusätzliche Details: Das Problem ist, dass die Version von color-convert, die du nutzt den exp operator (**) benutzt, der so erst ab Nodejs versionen nach 6.16 verfügbar ist. (es2016) Die von mir benutzte Version nutzt dafür noch math.pow. Was mir noch nicht ganz klar ist, ist der Fakt, warum das überhaupt installiert. color-convert definiert seine Abhängigkeit mit:  "node": ">=7.0.0". Also entweder NodesJs auf >=7.0.0 updaten,  oder color-convert auf <=1.9.3 downgraden.

**Comment by TheRegiiX** [comment]
Danke für deine Hilfe aber ich blicke langsam nicht mehr ganz durch.. hättest du ein kleines ssh commando für mich wie man den color-convert downgraded?

**Comment by ruhigundrelaxed** [comment]
ja, kann ich gleich machen, wenn ich zuhause bin.  Aber nur wenn du vorher ein aktuelles backup erstellt hast.

**Comment by ruhigundrelaxed** [comment]
Ok: Hier dann der Weg. Hab bei mir problemlos geklappt. (Upgrdade zu 2.0.0, da dann der gleiche Fehler wie bei dir und dann downgrade zu 1.9.2: funktioniert wieder)  1.) Gehe in den Ordner des Adapters: z.B.: "cd /opt/iobroker/node_modules/iobroker.hyperion" 2.) Downgrade zu 1.9.2: "npm install color-convert@1.9.2" Fertig... Bitte probieren und berichten. Danke & Gruß

**Comment by ruhigundrelaxed** [comment]
Ich gehe mal davon aus, dass das Problem behoben ist und mache hier zu...

**Comment by TheRegiiX** [comment]
Hey,
sorry bin grade dabei haha.
Ich hab nicht richtig gelesen hab mir die komplette installation kaputt gemacht ohne backup.
Bin grad dabei alles neu zu installieren.. diesesmal ist automatisch die node.js version 8.** installiert und damit klappts..super danke nochmal

**Comment by ruhigundrelaxed** [comment]
Oh man... Na gut.  Dann mach ich mich mal an: compact Mode, autodiscovery und hyperion.ng.

**Comment by TheRegiiX** [comment]
Ja war nervig aber nach den letzten 7 stunden sieht es langsam wieder nach was aus..vorallem hat man die möglichkeit es mal wieder ordentlich zu machen und hat nicht alles voller alter nutzlosen states und skripten.

Was auch immer das heißen soll..
Ich hab noch ne frage .. könnte man nicht vielleicht auch einen  ECHTEN an ausschalter für das ambilight einbauen?.. ich weiß nicht ob dies möglich ist aber man könnte doch vielleicht ein ssh commando an den pi mit hyperion schicken.
Das commando wäre ja nicht allzuschwer nur ich weiß nicht  ob man mit iobroker einfach so ssh commandos verschicken kann

**Comment by ruhigundrelaxed** [comment]
Warum willst du das denn tun? zieht hyperiond im standby irgendwas, ram oder cpu? Das wäre eher was für einen adapter der systemd units startet und stoppt.
