### ISSUE TITLE
State "clear" and "clearall" definition

### ISSUE THREAD

**Issue by OberfragGER** [ruhigundrelaxed/ioBroker.hyperion#31]
Hi,
i want to trigger the "button" via blockly, unfortunatly i recieve som errors when i want to switch off the light/ effects.

Goal: Just make it work via Yakha inside Homekit.

https://forum.iobroker.net/topic/28766/tastendruck-via-blockly-simulieren-ausl%C3%B6sen/10

`

You are assigning a boolean to the state "hyperion.0.control.clear" which expects a state. Please fix your code to use a state or change the state type to boolean. This warning might become an
--

Is it possible to fix that...?

`

**Comment by ruhigundrelaxed** [comment]
Hi, 
yes there were some wrong assignments of "common.type" which threw some warnings. I fixed that. Can you test, if this fixed your Problem? I usually don't use blockly and i'm therefore not familiar with it.

**Comment by OberfragGER** [comment]
> Hi,
> yes there were some wrong assignments of "common.type" which threw some warnings. I fixed that. Can you test, if this fixed your Problem? I usually don't use blockly and i'm therefore not familiar with it.

I will do so, but at the moment im not able to update the adapter.
When i try to deinstall... "some blabla" is marked not to be deleteable...
Also update via the the cat- some errors.

**Comment by ruhigundrelaxed** [comment]
yes. wait pls...

**Comment by OberfragGER** [comment]
> yes. wait pls...

check iobroker forum if you want to chat ;)

**Comment by ruhigundrelaxed** [comment]
fixed in 0.0.16
